GET http://localhost:5293/games

###

GET http://localhost:5293/games/5

###

POST http://localhost:5293/games
Content-Type: application/json

{
    "name": "FCk",
    "genreID": 1,
    "price": 29.99,
    "releaseDate": "2022-08-04"
}

###

PUT http://localhost:5293/games/6
Content-Type: application/json

{
    "name": "FUCK COZ WHY NOT??",
    "genreID": 1,
    "price": 49.99,
    "releaseDate": "2022-08-04"
}

###

DELETE http://localhost:5293/games/4


### 

GET http://localhost:5293/games/hello

###

GET http://localhost:5293/genre

###

GET http://localhost:5293/genre/1
